language: node_js

node_js:
  - 14

jobs:
  include:
    # Build the project
    - stage: build
      name: "Build SDK"
      script:
        - yarn build
    # Define the release stage that runs semantic-release
    - stage: release
      name: "Release new version of SDK"    
      node_js: lts/*
      # Advanced: optionally overwrite your default `script` step to skip the tests
      # script: skip
      deploy:
        provider: script
        skip_cleanup: true
        script:
          - npx semantic-release
