name: build-npm
on:
    pull_request:
    push:
        branches:
            - master
            - feature-*
            - develop
env:
    CODECOV_TOKEN: '${{ secrets.CODECOV_TOKEN }}'
    GITHUB_TOKEN: '${{ secrets.REACT_GITHUB_TOKEN }}'
    NPM_TOKEN: '${{ secrets.NPM_TOKEN }}'
defaults:
    run:
        shell: bash
jobs:
    test:
        name: Test 🧪
        runs-on: ubuntu-latest
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
            - uses: actions/cache@v2
              id: restore-build
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install --frozen-lockfile
            - run: yarn test
    build:
        name: Build ⚙️
        runs-on: ubuntu-latest
        needs: test
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
              with:
                  node-version: 12
            - uses: actions/cache@v2
              id: restore-build
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install --frozen-lockfile
            - run: yarn build
    publish:
        name: Publish 🚀
        runs-on: ubuntu-latest
        needs: build
        steps:
            - uses: actions/checkout@v2
            - uses: actions/setup-node@v2
            - uses: actions/cache@v2
              id: restore-build
              with:
                  path: '**/node_modules'
                  key: ${{ runner.os }}-modules-${{ hashFiles('**/yarn.lock') }}
            - run: yarn install --frozen-lockfile
            - uses: cycjimmy/semantic-release-action@v2.5.3
